http_server:
  host:
  port: 1313
  graceful_shutdown: 10s

o_auth:
  google:
    client_id:
    client_secret:

mongo_client:
  port: 27017
  #host: localhost
  host: mongodb-tonet
  username: root
  password: rootpassword

user_mongo:
  db_name: tonet
  coll_name: users

card_mongo:
  db_name: tonet
  coll_name: cards

visit_mongo:
  db_name: tonet
  coll_name: visits

auth:
  sign_key: mytonetsecretkey
  access_expiration_time: 2880h
  refresh_expiration_time: 3880h
  access_subject: acctoken
  refresh_subject: rftoken

minio:
 # endpoint: localhost:9000
  endpoint: minio-tonet:9002
  access_key_id: minio-root-user
  secret_access_key: minio-root-password
  use_ssl: false
  user_profile_bucket_name: user-profile
  card_profile_bucket_name: card-profile

card_config:
  create_card_limitation: 5

