http_server:
  host: localhost
  port: 1313
  graceful_shutdown: 5s

o_auth:
  google:
    client_id:
    client_secret:

mongo_client:
  port: 27017
  host: localhost
  username: root
  password: rootpassword

user_mongo:
  db_name: tonet
  coll_name: users

card_mongo:
  db_name: tonet
  coll_name: cards

auth:
  sign_key: mytonetsecretkey
  access_expiration_time: 24h
  RefreshExpirationTime: 48h
  access_subject: acctoken
  refresh_subject: rftoken

minio:
  endpoint: localhost:9000
  access_key_id: XrUDxIjBjGLq27swqIKN
  secret_access_key: 49N7PdgbVPGCnXpjHPnaHAllXche01WjzsxMSUYr
  use_ssl: false
  user_bucket_name: user-profile

