http_server:
  host:
  port: 1313
  graceful_shutdown: 5s

o_auth:
  google:
    client_id:
    client_secret:

mongo_client:
  port: 27017
  host: localhost
#  host: mongodb-tonet
  username: root
  password: rootpassword

user_mongo:
  db_name: tonet
  coll_name: users

card_mongo:
  db_name: tonet
  coll_name: cards

visit_mongo:
  db_name: tonet
  coll_name: visits

auth:
  sign_key: mytonetsecretkey
  access_expiration_time: 72h
  refresh_expiration_time: 124h
  access_subject: acctoken
  refresh_subject: rftoken

minio:
  endpoint: localhost:9000
#  endpoint: minio-tonet:9000
  access_key_id: minio-root-user
  secret_access_key: minio-root-password
  use_ssl: false
  user_bucket_name: user-profile

