# Use root/example as user/password credentials
version: '3.7'
services:
  mongodb:
    image: mongo:4.4.6
    restart: always
    container_name: mongodb-tonet
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_tonet:/data/db


  minio:
    image: 'bitnami/minio:2024.2.17'
    container_name: minio-tonet
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
    volumes:
      - minio_data_tonet:/data/minio

volumes:
  mongodb_data_tonet:
  minio_data_tonet: