# Use root/example as user/password credentials
version: '3.7'
services:
  mongodb-tonet:
    image: mongo:7.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: tonet
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_tonet:/data/db

volumes:
  mongodb_data_tonet: