# Use root/example as user/password credentials
version: '3.7'
services:
  tonet-core:
    build:
      context: .
      target: development
    image: tonet-core
    container_name: tonet-core
#    networks:
#      - core
    restart: always
    ports:
      - "1313:1313"
    depends_on:
      - "mongodb"
      - "minio"


  mongodb:
    image: mongo:7.0 # 7.0 for production 4.4.6 for vm
    restart: always
    container_name: mongodb-tonet
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
#    networks:
#      - core
    volumes:
      - mongodb_data_tonet:/data/db


  minio:
    image: minio/minio:RELEASE.2024-04-18T19-09-19Z-cpuv1
    container_name: minio-tonet
    ports:
      - 9002:9002
      - 9001:9001
    environment:
      - MINIO_ROOT_USER=minio-root-user
      - MINIO_ROOT_PASSWORD=minio-root-password
    volumes:
      - data1-1:/data1
      - data1-2:/data2
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 5s
      retries: 5
#    networks:
#      - core
    command: server --address ":9002" --console-address ":9001" http://minio/data{1...2}

volumes:
  mongodb_data_tonet:
  data1-1:
  data1-2:

#networks:
#  core:
#    driver: "bridge"